// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon/Supabase poolers multiplex connections and advisory locks time out (P1002).
    // Use DIRECT_URL (non-pooled) from Neon "Connection details" for migrate / db push.
    // Runtime app still uses DATABASE_URL in lib/db.ts (pooled is fine there).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
